#ifndef __SMCMACRO_H__
#define __SMCMACRO_H__
#include "smcmacroex.h"

#define CKT_INVALID				0			
#define CKT_USER				1			
#define CKT_NUM					2			


#define USERCHECK_YES			2			
#define USERCHECK_NO			1			
#define USERCHECK_INVALID		0		


#define SEND_SERVICE 0
#define RECV_SERVICE 1

#define ORG_ADDR 0
#define DEST_ADDR 1


#define tagCheckInfo\
	BYTE byCheckType;\
BYTE byUserCheck;  

struct struCheckInfo
{
	tagCheckInfo
		struCheckInfo()
	{
		byCheckType = CKT_USER;
		byUserCheck = USERCHECK_NO;
	}
	void operator = (struCheckInfo& check)
	{
		byCheckType = check.byCheckType;
		byUserCheck = check.byUserCheck;
	}
};	

struct struCheckInfos
{
	struCheckInfo 	 OrgCheckInfo; 
	struCheckInfo 	 DestCheckInfo; 
	void operator = (struCheckInfos& check)
	{
		OrgCheckInfo = check.OrgCheckInfo;
		DestCheckInfo = check.DestCheckInfo;
	}
};


typedef char* PTRMSG;

#define UC	unsigned char
#define US	unsigned short
#define UL	unsigned long


#define MAX_STATPARAM_LEN		14

#define UDHI_TYPE_NO            0
#define UDHI_TYPE_SMPP          10
#define UDHI_TYPE_INNER         20
#define UDHI_TYPE_SMS           30


#define DIR_SOURCE				1			
#define DIR_DEST				2		


#define DEFAULT_RESULT_FOR_DELIVER          0
#define USERCHECK_SOURCE        2          
#define USERCHECK_DEST          1           


#define NUMCHECK_NOPASS			2		
#define NUMCHECK_PASS			1		

#define MAX_ACCOUNTSECT_LEN         (20+1)  
#define MAX_CLIENTSECT_LEN          (20+1)
#define MAX_IF_NAME_LEN             (16+1)
#define MAX_ACCOUNTNAME_LEN			(20+1)
#define MAX_ACCOUNTPASSWORD_LEN		(8+1)

#define MAX_ACCOUNT_HAVE_IF_NUM		20
#define MAX_ACCESSCODE_NUM			200


#define MAX_IF_NUM				1000


#define MAX_PID					255

#define MAX_INTERFACEADDR_LEN		(40+1)
#define MAX_CODEPARAM_LEN			(40+1)

#define AR_INTEFACEMANAGER		0X00000001
#define AR_USERMANAGER			0X00000002
#define AR_STATISTIC			0X00000004

#define AR_SUBMIT				0X00000010
#define AR_DELIVER				0X00000020


#define AR_NORIGHT              0X00000000
#define AR_CONTROLRIGHT		    0X00000001
#define AR_QUERYRIGHT		    0X00000002 
#define ADMINISTRATOR_ID        "sa"

#define IFSTATEGY_FIRST			1
#define IFSTATEGY_ALTERNATE		2
#define IFSTATEGY_ACITVE        3

enum ENUM_BIND{
	BIND_SUCCESS = 0 ,
		BIND_FAIL,    
		BIND_INVALID_USER,  
		BIND_INVALID_PASSWORD,  
		BIND_USER_ALREADY_RIGISTERED,
		BIND_NEW_ERROR,
		BIND_INITIAL_FAIL,
		BIND_CONNECT_FAIL,
		BIND_NAME_ERROR,
		BIND_TYPE_ERROR,
		BIND_POCKET_ERROR,
		BIND_SEND_ERROR,
		BIND_TIMEOUT,
		BIND_ACK_ERROR,
		BIND_IF_REPEAT,
		BIND_OTHER_ERROR,
		
};
enum ENUM_SUBMIT_ACK{
	SUBMIT_SUCCESS=0,
		SUBMIT_OVER_MO, 
		SUBMIT_OVER_MT,	
		SUBMIT_INVALID_USER, 
		SUBMIT_INVALID_DATA_FORMAT, 
		SUBMIT_ADDR_ERROR, 
		SUBMIT_CREATE_MESSAGE_ERROR, 
		SUBMIT_OTHER_ERROR, 
		
};

enum E_ERROR_MSG
{
	E_SUCCESS = 0,
		
		
		E_ACCESSERR,		
		E_CALLERERR,	
		E_ACCOUNTERR,
		E_SMTYPEERR,
		E_NEWACCOUNTFAIL,
		E_ACCOUNTNAMEERR,
		E_CODETYPEERR,
		E_CREATEIFFAIL,		
		E_BEYONDMAXIFNUM,
		E_INVALIDIFID,
		E_ACCOUNTPASSWORDERR,
		E_NORIGHT,	
		E_PIDERR,
		E_INVALIDROUTETABLE,
		
		E_CANNOTFINDIF,	
		E_PARAMERR,	
		E_STATUSERR,
		
		E_INVALIDACCOUNT,
		
		E_INVALIDIF,
		
		
		E_NOSUBMITRIGHT,
		E_NODELIVERRIGHT,
		E_CHECKTYPEERR,			
		E_NUMREPEAT,			
		E_NOTHISNUM,			
		E_WATIACK,              
		E_DCS_ERROR,            
		E_SUBMIT_TIME_OUT,      
		E_SUBMIT_ERROR,         
		E_PARSER,               
		E_SERVICE_NOT_OPEN,    
		E_IF_STYLE,           
		E_ADDR_FOMRAT,         
		E_PARAM_NO,             
		E_BIND_SERVICEERR,    
		E_BUFFERERR,            
		E_ADD_TRACEERR,        
		E_CANCEL_TRACEERR,     
		E_ADD_STATERR,        
		E_STAT_TYPEERR,        
		E_STAT_NUMERR,        
		E_STAT_IDERR,          
		E_USER_SEND_FAIL,       
		E_USER_STATUS,          
		E_USER_TOMANY,          
		E_NO_PROMPT,           
		E_FAILED,              
		E_RESOURCE_LIMITED
};


#define MAX_QUERY_SMS_COUNT	100
#define SMS_QUERY_DIRECTION_ORG	0
#define SMS_QUERY_DIRECTION_DES	1
#define SMS_ACK_OK	0
#define SMS_ACK_ERROR	1

#define SHAKE_HAND_ERROR -188


#define MAX_STAT_VALUE_LEN  32

#define MAX_MOBILE_HEAD_LEN 8
#define MAX_STAT_ITEM_LEN   32
#define MAX_COUNTRYCODE_LEN 8
#define MAX_ADDR_LEN (20+1)
#define MAX_TIMESTAMP_LEN	(19+1)
#define MAX_SUB_ADDRESS (41+1)
//SMGW42-55, 2005-7-12, jdz, modi begin//
#define MAX_SM_LEN	(254+1)
//SMGW42-55, 2005-7-12, jdz, modi end//
#define MAX_UD_LEN  (140+1)
#define MAX_LONG_UD_LEN (40*1024)
#define MAX_LONG_SM_LEN	(40*1024)
#define UDH_LENGTH	6
#define MAX_CD_LEN	(156+1)
#define MAX_PASSWORD (9+1)
#define MAX_SM_INTERFACE_NAME_LEN 21
#define MAX_PARAM_NAME_LEN	30
#define MAX_MONITOR_PARAM_LEN 30
#define MAX_VALUE_LEN	1024
#define MAX_SERVICE	10
#define MAX_SM_NUM 100
#define MAX_IF_EXT_DATA 100
#define MAX_ACTIVE_TIME_LEN (8 + 1)

#define SMPP_ACK_OK		0	
#define SMPP_ACK_ERROR	1


#define IF_FLOW_CONTROL	3	
#define IF_TEMP_ERROR	2	
#define IF_INVALID		1	
#define IF_OK			0	

#define SM_STATE_FLOWCONTROL	0XFF


//	删除标志
#define DELSM_CAUSE_DEFORMITY		5	
#define DELSM_CAUSE_USER			4	
#define DELSM_CAUSE_COUNT_FLOW		3	
#define DELSM_CAUSE_TIMEOUT			2	
#define DELSM_CAUSE_FATAL_ERROR		1	
#define DELSM_DELIVER_OK			0	





#define IS_SMEI_ACK(ncommand) (ncommand&0x8000)
#define IS_IF_INNER_MSG(ncmd) (ncmd>=300)&&(ncmd<=399)
#define IS_TASKPOOL_MSG(ncmd) (ncmd>=400)&&(ncmd<=499)
#define IS_SMS_ACK(ncommand)  (ncommand&0x8000)


/////////////////////////////////////////////////////
//	消息类型定义
#define SMEI_SUBMIT_SM	0
#define SMEI_SUBMIT_SM_ACK	(SMEI_SUBMIT_SM|0x8000)
#define SMEI_SUBMIT_COMMAND	1
#define SMEI_DELIVER_SM	2
#define SMEI_DELIVER_SM_ACK	(SMEI_DELIVER_SM|0x8000)
#define SMEI_STATUS_REPORT	3
#define SMEI_ALERT_SC	4

// 查询消息
#define SMEI_QUERY_SM_STATUS	6
#define SMEI_QUERY_SM_STATUS_ACK	(SMEI_QUERY_SM_STATUS|0x8000)
#define SMEI_CANCEL_SM	13
#define SMEI_CANCEL_SM_ACK	(SMEI_CANCEL_SM|0x8000)
#define SMEI_REPLACE_SM	15
#define SMEI_REPLACE_SM_ACK	(SMEI_REPLACE_SM|0x8000)
#define SMEI_QUERY_MSGS	17
#define SMEI_QUERY_MSGS_ACK	(SMEI_QUERY_MSGS|0x8000)
#define SMEI_QUERY_MSG_DETAILS	19
#define SMEI_QUERY_MSG_DETAILS_ACK	(SMEI_QUERY_MSG_DETAILS|0x8000)

#define SMEI_REPLACE_SM_EX              16
#define SMEI_REPLACE_SM_EX_ACK          (SMEI_REPLACE_SM_EX|0X8000)
#define SMEI_QUERY_MSG_DETAILS_EX       20
#define SMEI_QUERY_MSG_DETAILS_EX_ACK   (SMEI_QUERY_MSG_DETAILS_EX|0X8000)


// 受理
#define SMEI_ADD_SUB	21
#define SMEI_ADD_SUB_ACK	(SMEI_ADD_SUB|0x8000)
#define SMEI_DEL_SUB	23
#define SMEI_DEL_SUB_ACK	(SMEI_DEL_SUB|0x8000)
#define SMEI_MOD_SUB	25
#define SMEI_MOD_SUB_ACK	(SMEI_MOD_SUB|0x8000)
#define SMEI_ENQUIRE_SUB	27
#define SMEI_ENQUIRE_SUB_ACK	(SMEI_ENQUIRE_SUB|0x8000)




//数据管理
#define SMEI_ADD_INTERFACE	300
#define SMEI_ADD_INTERFACE_ACK	SMEI_ADD_INTERFACE|0x8000
#define SMEI_DEL_INTERFACE	301
#define SMEI_DEL_INTERFACE_ACK	SMEI_DEL_INTERFACE|0x8000
#define SMEI_MOD_INTERFACE	302
#define SMEI_MOD_INTERFACE_ACK	SMEI_MOD_INTERFACE|0x8000
#define SMEI_ADD_SERVICE	303
#define SMEI_ADD_SERVICE_ACK	SMEI_ADD_SERVICE|0x8000
#define SMEI_DEL_SERVICE	304
#define SMEI_DEL_SERVICE_ACK	SMEI_DEL_SERVICE|0x8000

#define SMEI_QUERY_INTERFACE	305
#define SMEI_QUERY_INTERFACE_ACK	SMEI_QUERY_INTERFACE|0x8000
#define SMEI_QUERY_INTERFACES	306
#define SMEI_QUERY_INTERFACES_ACK	SMEI_QUERY_INTERFACES|0x8000

#define SMEI_IF_ERROR		307


#define SMEI_BIND_TRANSMITTER		308
#define SMEI_BIND_TRANSMITTER_ACK	(SMEI_BIND_TRANSMITTER|0x8000)
#define SMEI_BIND_RECEIVER			309
#define SMEI_BIND_RECEIVER_ACK		(SMEI_BIND_RECEIVER|0x8000)
#define SMEI_UNBIND		310
#define SMEI_UNBIND_ACK	SMEI_UNBIND|0x8000

#define SMEI_SET_IF_EXTINFO			322
#define SMEI_SET_IF_EXTINFO_ACK		SMEI_SET_IF_EXTINFO|0x8000
#define SMEI_GET_IF_EXTINFO			323
#define SMEI_GET_IF_EXTINFO_ACK		SMEI_SET_IF_EXTINFO|0x8000


#define SMEI_ENQUIRE_LINK 			324
#define SMEI_ENQUIRE_LINK_ACK	    (SMEI_ENQUIRE_LINK|0x8000)
#define SMEI_NACK					325


#define SMEI_SET_PARAM	400
#define SMEI_SET_PARAM_ACK	SMEI_SET_PARAM|0x8000
#define SMEI_QUERY_PARAM	401
#define SMEI_QUERY_PARAM_ACK	SMEI_QUERY_PARAM|0x8000
#define SMEI_MONITOR	402
#define SMEI_MONITOR_ACK	SMEI_MONITOR|0x8000
#define SMEI_MONITOR_INFO	403
#define SMEI_CANCEL_MONITOR	404
#define SMEI_CANCEL_MONITOR_ACK	SMEI_CANCEL_MONITOR|0x8000
#define SMEI_TRACE	405
#define SMEI_TRACE_ACK	SMEI_TRACE|0x8000
#define SMEI_TRACE_INFO	406
#define SMEI_CANCEL_TRACE	407
#define SMEI_CANCEL_TRACE_ACK	SMEI_CANCEL_TRACE|0x8000
#define SMEI_NEW_TASK	408
#define SMEI_NEW_TASK_ACK	SMEI_NEW_TASK|0x8000
#define SMEI_DEL_TASK	409
#define SMEI_DEL_TASK_ACK	SMEI_DEL_TASK|0x8000
#define SMEI_QUERY_TASK	410
#define SMEI_QUERY_TASK_ACK	SMEI_QUERY_TASK|0x8000
#define SMEI_GET_TASK_RECORD	411
#define SMEI_TASK_RECORD	412
#define SMEI_QUERY_TASKS	413
#define SMEI_QUERY_TASKS_ACK	SMEI_QUERY_TASKS|0x8000


#define SMEI_GATEWAY_MONITOR			414	
#define SMEI_GATEWAY_MONITOR_ACK		415 
#define SMEI_MONITORGATEWAY				416	
#define SMEI_MONITORGATEWAY_ACK			SMEI_MONITORGATEWAY|0x8000  
#define SMEI_CANCEL_MONITORGATEWAY		417  
#define SMEI_CANCEL_MONITORGATEWAY_ACK	SMEI_CANCEL_MONITORGATEWAY|0x8000 
#define SMEI_MONITORGATEWAY_INFO		418

#define SMEI_SET_ERRTIME				419
#define SMEI_SET_ERRTIME_ACK			SMEI_SET_ERRTIME|0x8000
#define SMEI_QUERY_ERRTIME				420
#define SMEI_QUERY_ERRTIME_ACK			SMEI_QUERY_ERRTIME|0x8000







#define SMEI_SMSMAP_MTDATA	MAKEWORD(204,0)
#define SMEI_SMSMAP_MTACK	MAKEWORD(204,1)
#define SMEI_SMSMAP_MTERROR	MAKEWORD(204,2)
#define SMEI_SMSMAP_MODATA	MAKEWORD(204,3)
#define SMEI_SMSMAP_MOACK	MAKEWORD(204,4)
#define SMEI_SMSMAP_MOERROR	MAKEWORD(204,5)
#define SMEI_SMSMAP_ALERTSC	MAKEWORD(204,6)
#define SMEI_SMSMAP_GATEWAY_MONITOR MAKEWORD(204,13)
#define SMEI_SMSMAP_GATEWAY_MONITOR_ACK MAKEWORD(204,14)


#define SMEI_TIME_TRIGGER	100
#define SMEI_DUMP_SM		101

enum ENUM_ADD_USER_STATUS
{
	USER_ALREADY_EXIST = 0,
		ADD_USER_SUCESS,
		ADD_USER_FAIL,
		ADD_USER_OTHER_ERROR,
};
enum ENUM_DEL_USER_STATUS
{
	USER_NOT_EXIST=0,
		USER_DEL_SUCCESS,
		USER_DEL_FAIL,
		DEL_USER_OTHER_ERROR,
};

enum ENUM_MOD_SUB_ACK{
	NO_THIS_SUB = 0,
		MODI_SUB_SUCCESS,
		MODI_SUB_FAIL,
		ERROR_OTHER_MODI_SUB,
};



#define SMEI_PPS_USER_CHECK	            0X01F4

#define SMEI_PPS_USER_CHECK_ACK	        0X81F4


#define SMEI_PPS_RESULT_NOTIFY	        0X01F5

#define SMEI_PPS_RESULT_NOTIFY_ACK	    0X81F5


#define SMEI_PPS_SUBMIT_SM	            0X01E


#define SMEI_PPS_ADD_DISTABLE	        0X0165

#define SMEI_PPS_ADD_DISTABLE_ACK	    0X8165


#define SMEI_PPS_DELETE_DISTABLE	    0X0166

#define SMEI_PPS_DELETE_DISTABLE_ACK	0X8166


#define SMEI_PPS_QUERY_ALL_ACCOUNT	    0X0167

#define SMEI_PPS_QUERY_ALL_ACCOUNT_ACK	0X8167


#define SMEI_PPS_QUERY_DISTABLE	        0X0168

#define SMEI_PPS_QUERY_DISTABLE_ACK	    0X8168



enum enumSMTType
{ 
    SMTYPE_WITHOUT_STATUS_REPORT = 0,
		SMTYPE_WITH_STATUS_REPORT,
		SMTYPE_STATUS_REPORT
};

enum enumChargeTypeStatusReport
{
    STATUS_REPORT_NOT_WRITE_CHARGE = 0,
		STATUS_REPORT_WRITE_CHARGE,
};


#endif
